This notebook representas the lab-task associated with data pre-processing.
Student Name:Pujan Sharma
Student ID: 1928447

In [19]:
# Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

numpy: NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays.</br>

matplotlib: Matplotlib is a plotting library for the Python programming language and its numerical mathematics extension NumPy. It provides an object-oriented API for embedding plots into applications using general-purpose GUI toolkits like Tkinter, wxPython, Qt, or GTK+.<br>

pyplot: matplotlib. pyplot is a collection of command style functions that make matplotlib work like MATLAB.

In [20]:
# Importing the dataset
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values

pd.read_csv: It retrieves data from csv file
dataset.iloc[:, :-1].values:  It retrieves the datas from first to secondlast column in the csv file. here the retrived value is assigned to X variable.
dataset.iloc[:, 3].values: It retrieves the datas from thrird columnin the csv file. here the retrived value is assigned to Y variable.



In [21]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

above data are the data in object X

In [22]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

above data shows the data in object y

In [23]:
# Taking care of missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

sklearn.impute: It is used to complete the missing values in the column.</br>

missing_values = np.nan :  It act as placeholder for missing value</br>

strategy = 'mean':  replace missing values using the mean along each column.</br>

imputer.fit : This fit  stores the mean value as calculated by simpleimputer in every rows from column 1 to 3, then uses it on test data during the transform.</br>
imputer.transform: It replaces the nan value with mean which is stored in imputer object.



In [24]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

Above output shows the datas in x object after missing values are replaced with the mean of datas from that particular column

In [25]:
# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

sklearn.preprocessing: It is python package provides several common utility functions and transformer classes to change raw feature vectors into a representation that is more suitable for the downstream estimators.</br>

LabelEncoder: Encode target labels with value between 0 and n_classes-1. In our case it is 0 to 2 and store in labelencoder_X object.
labelencoder_X.fit_transform(X[:, 0]): it provides encoded label to class in first column



In [26]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

It shows the x after labelENcoder is used in first column. The features are transformed into 0,1 and 2 from France germany Spanin respectively

In [27]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
np.set_printoptions(suppress = True)
print(X)

[[    1.             0.             0.            44.
  72000.        ]
 [    0.             0.             1.            27.
  48000.        ]
 [    0.             1.             0.            30.
  54000.        ]
 [    0.             0.             1.            38.
  61000.        ]
 [    0.             1.             0.            40.
  63777.77777778]
 [    1.             0.             0.            35.
  58000.        ]
 [    0.             0.             1.            38.77777778
  52000.        ]
 [    1.             0.             0.            48.
  79000.        ]
 [    0.             1.             0.            50.
  83000.        ]
 [    1.             0.             0.            37.
  67000.        ]]


C:\Users\pujan\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\pujan\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


OneHotencoder:Encode categorical features as a one-hot numeric array.(binary variables) here 0 is changed to 100, 2 to 001 and 1 to 010
categorical_features = [0]: it holds the categories expected in the first column</br>

onehotencoder.fit_transform(X).toarray()=  It retreaves the encoded array and transform the catagory with the encoded array.</br>

np.set_printoptions(suppress = True): suppresses the use of scientific notation for small numbers to 0



In [28]:
# Encoding the Dependent Variable
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

LabelEncoder: Encode target labels with value between 0 and n_classes-1. In our case it is 0 and 1 and store in labelencoder_y object.
labelencoder_y.fit_transform(y): replaces the velue of data with encoded value ie 0 and 1

In [29]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [30]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

sklearn.model_selection import train_test_split: Split arrays  into random train and test subsets
Here the  x and y datasets are splitted for training and testing in ratio 1:5

In [31]:
X_train

array([[    0.        ,     1.        ,     0.        ,    40.        ,
        63777.77777778],
       [    1.        ,     0.        ,     0.        ,    37.        ,
        67000.        ],
       [    0.        ,     0.        ,     1.        ,    27.        ,
        48000.        ],
       [    0.        ,     0.        ,     1.        ,    38.77777778,
        52000.        ],
       [    1.        ,     0.        ,     0.        ,    48.        ,
        79000.        ],
       [    0.        ,     0.        ,     1.        ,    38.        ,
        61000.        ],
       [    1.        ,     0.        ,     0.        ,    44.        ,
        72000.        ],
       [    1.        ,     0.        ,     0.        ,    35.        ,
        58000.        ]])

In [32]:
X_test

array([[    0.,     1.,     0.,    30., 54000.],
       [    0.,     1.,     0.,    50., 83000.]])

In [40]:

y_train= np.array(y_train).reshape(-1,1)
y_train



array([[1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1]])

In [34]:
y_test= np.array(y_test).reshape(-1,1)
y_test


array([[0],
       [0]])

In [41]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train)

StandardScaler: it is used for feature scaling. It changes the value of the feature by using the formula (x-Xmean)/sd of x   and same for y
fit_transform: it retrieves the new value and transforms the old value with new one.


In [42]:
X_test, y_test

(array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
        [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]]),
 array([[0],
        [0]]))

these are new value of x-test and y_test after feature scaling using standardscaler

In [43]:
X_train, y_train

(array([[-1.        ,  2.64575131, -0.77459667,  0.26306757,  0.12381479],
        [ 1.        , -0.37796447, -0.77459667, -0.25350148,  0.46175632],
        [-1.        , -0.37796447,  1.29099445, -1.97539832, -1.53093341],
        [-1.        , -0.37796447,  1.29099445,  0.05261351, -1.11141978],
        [ 1.        , -0.37796447, -0.77459667,  1.64058505,  1.7202972 ],
        [-1.        , -0.37796447,  1.29099445, -0.0813118 , -0.16751412],
        [ 1.        , -0.37796447, -0.77459667,  0.95182631,  0.98614835],
        [ 1.        , -0.37796447, -0.77459667, -0.59788085, -0.48214934]]),
 array([[ 0.77459667],
        [ 0.77459667],
        [ 0.77459667],
        [-1.29099445],
        [ 0.77459667],
        [-1.29099445],
        [-1.29099445],
        [ 0.77459667]]))

In [ ]:
these are new value of x-test and y_test after feature scalin using standardscaler